site_name: Amazon EKS SSP Quick Start
repo_name: "aws-quickstart/ssp-amazon-eks"
repo_url: "https://github.com/aws-quickstart/ssp-amazon-eks"
docs_dir: "docs"
theme: 
  name: material
  features: 
    - tabs
nav:
  - Overview: 'index.md'
  - Getting Started: 'getting-started.md'
  - Core Concepts: 'core-concepts.md'
  - Teams: 'teams.md'
  - Pipelines: 'pipelines.md'
  - AddOns:
    - Overview: 'addons/index.md'
    - AWS App Mesh: 'addons/app-mesh.md'
    - ArgoCD: 'addons/argo-cd.md'
    - AWS Load Balancer Controller: 'addons/aws-load-balancer-controller.md'
    - Calico: 'addons/calico.md'
    - Cluster Autoscaler: 'addons/cluster-autoscaler.md'
    - Container Insights: 'addons/container-insights.md'
    - External DNS: 'addons/external-dns.md'
    - Metrics Server: 'addons/metrics-server.md'
    - Nginx: 'addons/nginx.md'
    - SSM Agent: 'addons/ssm-agent.md'
    - Secrets Store: 'addons/secrets-store.md'
    - Weave GitOps: 'https://github.com/weaveworks/weave-gitops-ssp-addon'
    - AWS XRay: 'addons/xray.md'
  - Cluster Providers: 
    - Overview: 'cluster-providers/index.md'
    - ASG Cluster Provider: 'cluster-providers/asg-cluster-provider.md'
    - MNG Cluster Provider: 'cluster-providers/mng-cluster-provider.md'
    - Fargate Cluster Provider: 'cluster-providers/fargate-cluster-provider.md'
markdown_extensions:
  - def_list
  - pymdownx.highlight  
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
plugins:
  - search